### ISSUE TITLE
Error when trying to run

### ISSUE THREAD

**Issue by hiniesta** [fmoessle/angular2-webrtc#37]
I get this error when trying to compile it:
npm ERR! code E404
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/angular-webpack2-starter
npm ERR! 404 
npm ERR! 404  'angular-webpack2-starter' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by tuduong1** [comment]
I got this error when run npm start
Node v8.1.2 (npm v5.0.3)


`/home/tu/Documents/Project/angular2-webrtc/node_modules/ts-node/src/index.ts:312
          throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
                ^
TSError: ⨯ Unable to compile TypeScript
webpack.config.ts (114,38): Property 'assign' does not exist on type 'ObjectConstructor'. (2339)
webpack.config.ts (212,38): Property 'assign' does not exist on type 'ObjectConstructor'. (2339)
webpack.config.ts (288,12): Property 'assign' does not exist on type 'ObjectConstructor'. (2339)
    at getOutput (/home/tu/Documents/Project/angular2-webrtc/node_modules/ts-node/src/index.ts:312:17)
    at /home/tu/Documents/Project/angular2-webrtc/node_modules/ts-node/src/index.ts:343:18
    at Object.compile (/home/tu/Documents/Project/angular2-webrtc/node_modules/ts-node/src/index.ts:476:19)
    at Module.m._compile (/home/tu/Documents/Project/angular2-webrtc/node_modules/ts-node/src/index.ts:406:44)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/tu/Documents/Project/angular2-webrtc/node_modules/ts-node/src/index.ts:409:12)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-webpack2-starter@1.13.0 webdev: `webpack-dev-server "--inline" "--hot"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-webpack2-starter@1.13.0 webdev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tu/.npm/_logs/2017-06-16T10_40_07_214Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-webpack2-starter@1.13.0 webdev:hmr: `npm run webdev -- --inline --hot`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-webpack2-starter@1.13.0 webdev:hmr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tu/.npm/_logs/2017-06-16T10_40_07_230Z-debug.log
ERROR: "webdev:hmr" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-webpack2-starter@1.13.0 server:hmr: `npm-run-all -p -r webdev:hmr sass:watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-webpack2-starter@1.13.0 server:hmr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tu/.npm/_logs/2017-06-16T10_40_07_272Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-webpack2-starter@1.13.0 start: `npm run server:hmr`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-webpack2-starter@1.13.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tu/.npm/_logs/2017-06-16T10_40_07_283Z-debug.log
`
